/**
 * XR — Universal Provider Presets
 * Built-in metadata for every supported provider. Never hardcode outside this file.
 */

import type { ProviderCapabilities } from "./capabilities.ts";

export type ProviderKind = "hosted" | "local" | "custom";
export type CostTier = "free" | "cheap" | "premium" | "enterprise";

export interface ProviderPreset {
  id: string;
  label: string;
  kind: ProviderKind;
  tier: CostTier;
  baseUrl?: string;
  apiKeyEnv?: string;
  authType?: "none" | "bearer" | "apiKey" | "aws" | "google" | "multi";
  defaultModel: string;
  knownModels: string[];
  capabilities: ProviderCapabilities;
  description?: string;
  docsUrl?: string;
  headers?: Record<string, string>;
}

function caps(p: Partial<ProviderCapabilities>): ProviderCapabilities {
  return { chat: true, ...p };
}

export const PRESETS: Record<string, ProviderPreset> = {
  // ── LOCAL / SELF-HOSTED ─────────────────────────────────────────────────────
  ollama: {
    id: "ollama",
    label: "Ollama (Local)",
    kind: "local",
    tier: "free",
    baseUrl: "http://localhost:11434/v1",
    apiKeyEnv: undefined,
    authType: "none",
    defaultModel: "qwen2.5:7b",
    knownModels: [
      "qwen2.5:3b",
      "phi3:mini",
      "qwen2.5:7b",
      "llama3.1:8b",
      "qwen2.5:14b",
      "qwen2.5:32b",
      "mistral:7b",
      "codellama:7b",
      "gemma2:9b",
    ],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "Self-hosted local models via Ollama. Zero cost, runs on your hardware.",
    docsUrl: "https://ollama.com",
  },
  lmstudio: {
    id: "lmstudio",
    label: "LM Studio (Local)",
    kind: "local",
    tier: "free",
    baseUrl: "http://localhost:1234/v1",
    apiKeyEnv: undefined,
    authType: "none",
    defaultModel: "lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF",
    knownModels: [],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "LM Studio local server with OpenAI-compatible API.",
    docsUrl: "https://lmstudio.ai",
  },
  jan: {
    id: "jan",
    label: "Jan (Local)",
    kind: "local",
    tier: "free",
    baseUrl: "http://localhost:1337/v1",
    apiKeyEnv: undefined,
    authType: "none",
    defaultModel: "jan",
    knownModels: [],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "Jan local AI assistant with built-in model management.",
    docsUrl: "https://jan.ai",
  },
  localai: {
    id: "localai",
    label: "LocalAI (Local)",
    kind: "local",
    tier: "free",
    baseUrl: "http://localhost:8080/v1",
    apiKeyEnv: undefined,
    authType: "none",
    defaultModel: "gpt-4",
    knownModels: [],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "OpenAI-compatible wrapper for local model inference.",
    docsUrl: "https://localai.io",
  },
  vllm: {
    id: "vllm",
    label: "vLLM (Local)",
    kind: "local",
    tier: "free",
    baseUrl: "http://localhost:8000/v1",
    apiKeyEnv: undefined,
    authType: "none",
    defaultModel: "meta-llama/Llama-3.1-8B-Instruct",
    knownModels: [],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "High-throughput local inference server with OpenAI-compatible API.",
    docsUrl: "https://docs.vllm.ai",
  },

  // ── FREE CLOUD TIER ─────────────────────────────────────────────────────────
  groq: {
    id: "groq",
    label: "Groq (Fast)",
    kind: "hosted",
    tier: "free",
    baseUrl: "https://api.groq.com/openai/v1",
    apiKeyEnv: "GROQ_API_KEY",
    authType: "bearer",
    defaultModel: "llama-3.3-70b-versatile",
    knownModels: [
      "llama-3.3-70b-versatile",
      "llama-3.1-8b-instant",
      "mixtral-8x7b-32768",
      "gemma2-9b-it",
    ],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "Blazing fast inference on open-source models. Generous free tier.",
    docsUrl: "https://groq.com",
  },
  google: {
    id: "google",
    label: "Google Gemini",
    kind: "hosted",
    tier: "free",
    apiKeyEnv: "GOOGLE_API_KEY",
    authType: "apiKey",
    defaultModel: "gemini-1.5-flash",
    knownModels: [
      "gemini-2.0-flash",
      "gemini-1.5-flash",
      "gemini-1.5-flash-8b",
      "gemini-1.5-pro",
      "gemini-pro",
      "gemini-pro-vision",
    ],
    capabilities: caps({ toolUse: true, vision: true, jsonMode: true, streaming: true, embeddings: true }),
    description: "Google Gemini with free tier (15 req/min). Vision and long-context support.",
    docsUrl: "https://ai.google.dev",
  },
  deepseek: {
    id: "deepseek",
    label: "DeepSeek",
    kind: "hosted",
    tier: "free",
    baseUrl: "https://api.deepseek.com/v1",
    apiKeyEnv: "DEEPSEEK_API_KEY",
    authType: "bearer",
    defaultModel: "deepseek-chat",
    knownModels: ["deepseek-chat", "deepseek-coder"],
    capabilities: caps({ reasoning: true, jsonMode: true, streaming: true }),
    description: "Affordable Chinese reasoning models. Very low cost.",
    docsUrl: "https://platform.deepseek.com",
  },
  cerebras: {
    id: "cerebras",
    label: "Cerebras",
    kind: "hosted",
    tier: "free",
    baseUrl: "https://api.cerebras.ai/v1",
    apiKeyEnv: "CEREBRAS_API_KEY",
    authType: "bearer",
    defaultModel: "cerebras/csm-8b",
    knownModels: ["cerebras/csm-8b"],
    capabilities: caps({ streaming: true }),
    description: "Fastest inference available. Free tier with generous limits.",
    docsUrl: "https://cerebras.ai",
  },

  // ── CHEAP CLOUD TIER ───────────────────────────────────────────────────────
  openrouter: {
    id: "openrouter",
    label: "OpenRouter",
    kind: "hosted",
    tier: "cheap",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyEnv: "OPENROUTER_API_KEY",
    authType: "bearer",
    defaultModel: "anthropic/claude-3.5-sonnet",
    knownModels: [
      "anthropic/claude-3.5-sonnet",
      "openai/gpt-4o",
      "google/gemini-2.0-flash-exp",
      "meta-llama/llama-3.3-70b-instruct",
    ],
    capabilities: caps({ toolUse: true, vision: true, jsonMode: true, streaming: true }),
    description: "Unified gateway to 200+ models. One key, many providers.",
    docsUrl: "https://openrouter.ai",
  },
  together: {
    id: "together",
    label: "Together AI",
    kind: "hosted",
    tier: "cheap",
    baseUrl: "https://api.together.xyz/v1",
    apiKeyEnv: "TOGETHER_API_KEY",
    authType: "bearer",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    knownModels: [
      "meta-llama/Llama-3.3-70B-Instruct-Turbo",
      "meta-llama/Llama-3.1-8B-Instruct-Turbo",
      "mistralai/Mixtral-8x7B-Instruct-v0.1",
    ],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "Cheap open-source model inference. Good for experimentation.",
    docsUrl: "https://together.ai",
  },
  mistral: {
    id: "mistral",
    label: "Mistral AI",
    kind: "hosted",
    tier: "cheap",
    apiKeyEnv: "MISTRAL_API_KEY",
    authType: "bearer",
    defaultModel: "mistral-small-latest",
    knownModels: [
      "mistral-large-latest",
      "mistral-medium-latest",
      "mistral-small-latest",
      "codestral-latest",
      "open-mixtral-8x7b",
    ],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "European LLM provider. Excellent coding models.",
    docsUrl: "https://mistral.ai",
  },
  fireworks: {
    id: "fireworks",
    label: "Fireworks AI",
    kind: "hosted",
    tier: "cheap",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    apiKeyEnv: "FIREWORKS_API_KEY",
    authType: "bearer",
    defaultModel: "accounts/fireworks/models/llama-v3p1-70b-instruct",
    knownModels: [],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "Fast inference for open-source models. Competitive pricing.",
    docsUrl: "https://fireworks.ai",
  },
  sambanova: {
    id: "sambanova",
    label: "SambaNova",
    kind: "hosted",
    tier: "cheap",
    baseUrl: "https://api.sambanova.ai/v1",
    apiKeyEnv: "SAMBANOVA_API_KEY",
    authType: "bearer",
    defaultModel: "Meta-Llama-3.1-70B-Instruct",
    knownModels: [],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true }),
    description: "Enterprise AI inference platform with fast throughput.",
    docsUrl: "https://sambanova.ai",
  },
  huggingface: {
    id: "huggingface",
    label: "Hugging Face",
    kind: "hosted",
    tier: "cheap",
    baseUrl: "https://api-inference.huggingface.co/v1",
    apiKeyEnv: "HF_API_KEY",
    authType: "bearer",
    defaultModel: "meta-llama/Llama-3.1-8B-Instruct",
    knownModels: [],
    capabilities: caps({ chat: true, jsonMode: true, streaming: true }),
    description: "Inference API for thousands of models. Serverless and dedicated endpoints.",
    docsUrl: "https://huggingface.co/inference-api",
  },

  // ── PREMIUM TIER ───────────────────────────────────────────────────────────
  openai: {
    id: "openai",
    label: "OpenAI",
    kind: "hosted",
    tier: "premium",
    baseUrl: "https://api.openai.com/v1",
    apiKeyEnv: "OPENAI_API_KEY",
    authType: "bearer",
    defaultModel: "gpt-4o-mini",
    knownModels: [
      "gpt-4o",
      "gpt-4o-mini",
      "gpt-4-turbo",
      "gpt-3.5-turbo",
      "o1-preview",
      "o1-mini",
      "gpt-4.1",
      "gpt-4.1-mini",
    ],
    capabilities: caps({
      toolUse: true,
      vision: true,
      jsonMode: true,
      streaming: true,
      functionCalling: true,
      embeddings: true,
    }),
    description: "Industry standard. GPT-4o, o1, and embeddings. Best quality/cost balance.",
    docsUrl: "https://platform.openai.com",
  },
  anthropic: {
    id: "anthropic",
    label: "Anthropic Claude",
    kind: "hosted",
    tier: "premium",
    apiKeyEnv: "ANTHROPIC_API_KEY",
    authType: "apiKey",
    defaultModel: "claude-3-5-sonnet-20241022",
    knownModels: [
      "claude-3-5-sonnet-20241022",
      "claude-3-opus-20240229",
      "claude-3-sonnet-20240229",
      "claude-3-haiku-20240307",
      "claude-3-7-sonnet-20250219",
    ],
    capabilities: caps({ toolUse: true, vision: true, jsonMode: true, streaming: true }),
    description: "Best-in-class reasoning and safety. Excellent for complex tasks.",
    docsUrl: "https://www.anthropic.com",
  },
  cohere: {
    id: "cohere",
    label: "Cohere",
    kind: "hosted",
    tier: "premium",
    apiKeyEnv: "COHERE_API_KEY",
    authType: "bearer",
    defaultModel: "command-r-plus-08-2024",
    knownModels: [
      "command-r-plus-08-2024",
      "command-r-08-2024",
      "command",
    ],
    capabilities: caps({ toolUse: true, jsonMode: true, streaming: true, embeddings: true }),
    description: "Long-context specialists. Command R+ is excellent for RAG and documents.",
    docsUrl: "https://cohere.com",
  },
  xai: {
    id: "xai",
    label: "xAI (Grok)",
    kind: "hosted",
    tier: "premium",
    baseUrl: "https://api.x.ai/v1",
    apiKeyEnv: "XAI_API_KEY",
    authType: "bearer",
    defaultModel: "grok-2-latest",
    knownModels: [
      "grok-2-latest",
      "grok-2-vision-latest",
      "grok-beta",
    ],
    capabilities: caps({ toolUse: true, vision: true, jsonMode: true, streaming: true }),
    description: "xAI Grok models. Vision and real-time data capabilities.",
    docsUrl: "https://x.ai/api",
  },
  perplexity: {
    id: "perplexity",
    label: "Perplexity",
    kind: "hosted",
    tier: "premium",
    baseUrl: "https://api.perplexity.ai",
    apiKeyEnv: "PERPLEXITY_API_KEY",
    authType: "bearer",
    defaultModel: "llama-3.1-sonar-large-128k-online",
    knownModels: [
      "llama-3.1-sonar-large-128k-online",
      "llama-3.1-sonar-small-128k-online",
      "llama-3.1-sonar-pro-128k-online",
    ],
    capabilities: caps({ chat: true, jsonMode: true, streaming: true }),
    description: "Search-augmented LLM. Real-time citations and web search.",
    docsUrl: "https://perplexity.ai",
  },

  // ── ENTERPRISE TIER ─────────────────────────────────────────────────────────
  bedrock: {
    id: "bedrock",
    label: "AWS Bedrock",
    kind: "hosted",
    tier: "enterprise",
    apiKeyEnv: undefined,
    authType: "aws",
    defaultModel: "claude-3-sonnet",
    knownModels: [
      "claude-3-sonnet",
      "claude-3-opus",
      "claude-3-haiku",
      "llama-3-70b",
      "mistral-large",
      "command-r-plus",
    ],
    capabilities: caps({ toolUse: true, vision: true, jsonMode: true, streaming: true }),
    description: "AWS-managed model access. IAM roles, VPC support, enterprise compliance.",
    docsUrl: "https://aws.amazon.com/bedrock",
  },
};
