/*
 * Generates src/data/licenses.ts from desktop/node_modules.
 * Run: cd desktop && bun run scripts/generate-licenses.ts
 */
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

interface Entry {
  name: string;
  version: string;
  license: string;
  homepage?: string;
}

const desktopRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const nodeModules = join(desktopRoot, 'node_modules');

function readPackage(pkgPath: string): Record<string, unknown> | null {
  try {
    return JSON.parse(readFileSync(pkgPath, 'utf8')) as Record<string, unknown>;
  } catch {
    return null;
  }
}

const entries = new Map<string, Entry>();

const add = (pkg: Record<string, unknown> | null): void => {
  const name = typeof pkg?.name === 'string' ? pkg.name : null;
  if (!name || name.startsWith('@rrrtx/')) return;
  entries.set(name, {
    name,
    version: typeof pkg?.version === 'string' ? pkg.version : '',
    license:
      typeof pkg?.license === 'string'
        ? pkg.license
        : 'UNKNOWN',
    homepage: typeof pkg?.homepage === 'string' ? pkg.homepage : undefined,
  });
};

for (const name of readdirSync(nodeModules)) {
  if (name.startsWith('.')) continue;
  const dir = join(nodeModules, name);
  if (!statSync(dir).isDirectory()) continue;
  if (name.startsWith('@')) {
    for (const pkg of readdirSync(dir)) {
      add(readPackage(join(dir, pkg, 'package.json')));
    }
  } else {
    add(readPackage(join(dir, 'package.json')));
  }
}

const list = [...entries.values()].sort((a, b) => a.name.localeCompare(b.name));

const out = `/*
 * GENERATED by scripts/generate-licenses.ts — do not edit by hand.
 * ${list.length} packages from desktop/node_modules at generation time.
 */
export interface LicenseEntry {
  name: string;
  version: string;
  license: string;
  homepage?: string;
}

export const THIRD_PARTY_LICENSES: readonly LicenseEntry[] = [
${list
  .map(
    (entry) =>
      `  { name: ${JSON.stringify(entry.name)}, version: ${JSON.stringify(entry.version)}, license: ${JSON.stringify(entry.license)}${entry.homepage ? `, homepage: ${JSON.stringify(entry.homepage)}` : ''} },`
  )
  .join('\n')}
];
`;

mkdirSync(join(desktopRoot, 'src/data'), { recursive: true });
writeFileSync(join(desktopRoot, 'src/data/licenses.ts'), out);
console.log(`licenses.ts written: ${list.length} entries`);
