import {
  Code2,
  Terminal,
  GitBranch,
  Search,
  FileCode2,
  Cloud,
  Database,
  Cpu,
  ShieldCheck,
  Boxes,
  Zap,
  Workflow,
  Lock,
  LineChart,
  Palette,
  Globe,
  Wrench,
  BookOpen,
  Rocket,
} from "lucide-react";

export const features = [
  {
    icon: Cpu,
    title: "Agentic Runtime",
    desc: "A performant, sandboxed runtime that plans, executes, and iterates — with deterministic replays and full audit trails.",
  },
  {
    icon: Terminal,
    title: "Native Shell",
    desc: "XR lives inside your terminal. Native commands, pipes, and a sub-10ms cold start. No browser required.",
  },
  {
    icon: Code2,
    title: "Editor Agnostic",
    desc: "First-class integrations with VS Code, Neovim, JetBrains, Zed, and Cursor. Your agent, every surface.",
  },
  {
    icon: Boxes,
    title: "Skill Graph",
    desc: "Compose 12,000+ verified skills into pipelines. Each skill is typed, versioned, and permission-scoped.",
  },
  {
    icon: Cloud,
    title: "Any Model",
    desc: "Open-weight to frontier — GPT-5, Claude Opus, Gemini, DeepSeek, Qwen, Llama, Groq. Route by cost, latency, or task.",
  },
  {
    icon: ShieldCheck,
    title: "Security by Default",
    desc: "Capability-based security, human-in-the-loop confirmations, signed skills, and end-to-end audit logging.",
  },
  {
    icon: GitBranch,
    title: "Reproducible Workflows",
    desc: "Every run is a replayable trace. Share sessions, diff executions, and roll agents back like code.",
  },
  {
    icon: Workflow,
    title: "MCP Native",
    desc: "Use any Model Context Protocol server out of the box. Build your own MCP tools with a single file.",
  },
  {
    icon: Zap,
    title: "Blazing Fast",
    desc: "Rust core. Streaming by default. Sub-second tool calls on local models. Designed for daily driving.",
  },
];

export const stats = [
  { value: "12.4M", label: "Monthly runs" },
  { value: "12,000+", label: "Verified skills" },
  { value: "840K+", label: "Developers" },
  { value: "99.99%", label: "Uptime (Cloud)" },
];

export const logos = [
  "Vercel",
  "Linear",
  "Raycast",
  "Anthropic",
  "Cursor",
  "Warp",
  "Supabase",
  "Replicate",
  "Perplexity",
  "Resend",
  "Notion",
  "Stripe",
];

export const marketplaceCategories = [
  { id: "all", label: "All" },
  { id: "coding", label: "Coding" },
  { id: "devops", label: "DevOps" },
  { id: "data", label: "Data" },
  { id: "design", label: "Design" },
  { id: "productivity", label: "Productivity" },
  { id: "research", label: "Research" },
  { id: "writing", label: "Writing" },
  { id: "security", label: "Security" },
  { id: "web", label: "Web" },
];

type ItemType = "skill" | "extension";

export interface MarketplaceItem {
  id: string;
  name: string;
  tagline: string;
  description: string;
  type: ItemType;
  category: string;
  author: string;
  authorHandle: string;
  verified: boolean;
  downloads: number;
  rating: number;
  reviews: number;
  version: string;
  compatibility: string;
  icon: React.ComponentType<{ className?: string }>;
  iconBg: string;
  installs: string;
  updated: string;
  installCmd: string;
  tags: string[];
}

export const marketplaceItems: MarketplaceItem[] = [
  {
    id: "pr-reviewer",
    name: "PR Reviewer",
    tagline: "Review pull requests with context-aware analysis",
    description:
      "Scans diffs, links to tickets, flags risky changes, and drafts review comments with code suggestions. Supports GitHub, GitLab, and Bitbucket.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    authorHandle: "@xr",
    verified: true,
    downloads: 1_240_000,
    rating: 4.9,
    reviews: 3421,
    version: "2.4.1",
    compatibility: "XR 3.0+",
    icon: GitBranch,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "1.2M",
    updated: "2 days ago",
    installCmd: "xr skills add pr-reviewer",
    tags: ["git", "code-review", "github"],
  },
  {
    id: "code-search",
    name: "Codebase Search",
    tagline: "Semantic search across your entire repo",
    description:
      "Indexes your codebase locally and answers questions across files, functions, and commits. Reranks by symbol relevance.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    authorHandle: "@xr",
    verified: true,
    downloads: 980_000,
    rating: 4.8,
    reviews: 2104,
    version: "1.9.0",
    compatibility: "XR 3.0+",
    icon: Search,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "980K",
    updated: "5 days ago",
    installCmd: "xr skills add code-search",
    tags: ["search", "embeddings", "indexing"],
  },
  {
    id: "refactor",
    name: "Smart Refactor",
    tagline: "Automated refactors with type-safe transforms",
    description:
      "Performs AST-guided renames, module splits, and dependency cleanup. Generates PRs with before/after diffs.",
    type: "skill",
    category: "coding",
    author: "Hermes Labs",
    authorHandle: "@hermes",
    verified: true,
    downloads: 540_000,
    rating: 4.7,
    reviews: 1203,
    version: "3.1.2",
    compatibility: "XR 3.1+",
    icon: FileCode2,
    iconBg: "linear-gradient(135deg,#f472b6,#f59e0b)",
    installs: "540K",
    updated: "1 week ago",
    installCmd: "xr skills add smart-refactor",
    tags: ["refactor", "typescript", "ast"],
  },
  {
    id: "deploy",
    name: "One-Click Deploy",
    tagline: "Deploy to Vercel, Cloudflare, AWS, Fly.io",
    description:
      "Detects your stack, provisions infra, configures CI, and ships preview environments. Rollback with a command.",
    type: "extension",
    category: "devops",
    author: "XR Official",
    authorHandle: "@xr",
    verified: true,
    downloads: 720_000,
    rating: 4.8,
    reviews: 1876,
    version: "2.0.0",
    compatibility: "XR 3.0+",
    icon: Rocket,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "720K",
    updated: "3 days ago",
    installCmd: "xr extensions add deploy",
    tags: ["deploy", "vercel", "cloud"],
  },
  {
    id: "db-browser",
    name: "Database Studio",
    tagline: "Browsing, migrations, and query explain",
    description:
      "Connect to Postgres, MySQL, SQLite, MongoDB, Supabase, Turso, and Neon. Generate type-safe migrations.",
    type: "extension",
    category: "data",
    author: "DataStream",
    authorHandle: "@datastream",
    verified: true,
    downloads: 310_000,
    rating: 4.6,
    reviews: 684,
    version: "1.4.3",
    compatibility: "XR 3.0+",
    icon: Database,
    iconBg: "linear-gradient(135deg,#8b5cf6,#ec4899)",
    installs: "310K",
    updated: "2 weeks ago",
    installCmd: "xr extensions add db-studio",
    tags: ["database", "sql", "migrations"],
  },
  {
    id: "security-audit",
    name: "Security Audit",
    tagline: "SAST, dependency, and secret scanning",
    description:
      "Scans repos for vulnerabilities, leaked secrets, and supply-chain risks. Produces SARIF reports.",
    type: "skill",
    category: "security",
    author: "LockShield",
    authorHandle: "@lockshield",
    verified: true,
    downloads: 220_000,
    rating: 4.9,
    reviews: 412,
    version: "1.2.8",
    compatibility: "XR 3.1+",
    icon: Lock,
    iconBg: "linear-gradient(135deg,#ef4444,#f97316)",
    installs: "220K",
    updated: "4 days ago",
    installCmd: "xr skills add security-audit",
    tags: ["security", "sast", "secrets"],
  },
  {
    id: "design-tokens",
    name: "Design Tokens",
    tagline: "Sync design tokens from Figma to code",
    description:
      "Pulls styles, typography scales, and color systems from Figma and emits Tailwind / CSS / Swift / Compose.",
    type: "extension",
    category: "design",
    author: "Palette",
    authorHandle: "@palette",
    verified: false,
    downloads: 84_000,
    rating: 4.5,
    reviews: 198,
    version: "0.9.4",
    compatibility: "XR 3.0+",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#ec4899,#a855f7)",
    installs: "84K",
    updated: "6 days ago",
    installCmd: "xr extensions add design-tokens",
    tags: ["figma", "design", "tokens"],
  },
  {
    id: "research-deep",
    name: "Deep Research",
    tagline: "Multi-source research with citations",
    description:
      "Performs iterative web research, synthesizes findings, and outputs cited reports. Supports arXiv and academic APIs.",
    type: "skill",
    category: "research",
    author: "XR Official",
    authorHandle: "@xr",
    verified: true,
    downloads: 610_000,
    rating: 4.9,
    reviews: 2341,
    version: "2.1.0",
    compatibility: "XR 3.0+",
    icon: BookOpen,
    iconBg: "linear-gradient(135deg,#14b8a6,#6366f1)",
    installs: "610K",
    updated: "1 day ago",
    installCmd: "xr skills add deep-research",
    tags: ["research", "web", "citations"],
  },
  {
    id: "docs-writer",
    name: "Docs Writer",
    tagline: "Auto-generate docs from code",
    description:
      "Generates READMEs, TSDoc, JSDoc, OpenAPI specs, and MDX guides. Keeps docs in sync on every commit.",
    type: "skill",
    category: "writing",
    author: "DocForge",
    authorHandle: "@docforge",
    verified: true,
    downloads: 290_000,
    rating: 4.7,
    reviews: 541,
    version: "1.7.2",
    compatibility: "XR 3.0+",
    icon: BookOpen,
    iconBg: "linear-gradient(135deg,#0ea5e9,#22c55e)",
    installs: "290K",
    updated: "2 weeks ago",
    installCmd: "xr skills add docs-writer",
    tags: ["docs", "tsdoc", "openapi"],
  },
  {
    id: "web-preview",
    name: "Live Preview",
    tagline: "Instant browser preview with hot reload",
    description:
      "Spins up a sandboxed browser for your web app. Captures screenshots, runs Lighthouse, and flags regressions.",
    type: "extension",
    category: "web",
    author: "XR Official",
    authorHandle: "@xr",
    verified: true,
    downloads: 420_000,
    rating: 4.6,
    reviews: 912,
    version: "1.5.0",
    compatibility: "XR 3.1+",
    icon: Globe,
    iconBg: "linear-gradient(135deg,#f59e0b,#ef4444)",
    installs: "420K",
    updated: "1 week ago",
    installCmd: "xr extensions add live-preview",
    tags: ["browser", "preview", "lighthouse"],
  },
  {
    id: "metrics",
    name: "Metrics Dashboard",
    tagline: "Real-time telemetry for your agents",
    description:
      "Tracks token usage, tool calls, success rates, and cost. Emits OpenTelemetry to your favorite backend.",
    type: "extension",
    category: "devops",
    author: "TraceLine",
    authorHandle: "@traceline",
    verified: true,
    downloads: 140_000,
    rating: 4.5,
    reviews: 302,
    version: "1.1.0",
    compatibility: "XR 3.1+",
    icon: LineChart,
    iconBg: "linear-gradient(135deg,#06b6d4,#8b5cf6)",
    installs: "140K",
    updated: "3 weeks ago",
    installCmd: "xr extensions add metrics",
    tags: ["otel", "telemetry", "cost"],
  },
  {
    id: "toolkit",
    name: "Productivity Toolkit",
    tagline: "Calendar, email, Slack, Notion, Linear",
    description:
      "Connects your daily tools. Reads mail, drafts replies, triages Linear issues, and summarizes Slack threads.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    authorHandle: "@xr",
    verified: true,
    downloads: 890_000,
    rating: 4.8,
    reviews: 2810,
    version: "3.0.1",
    compatibility: "XR 3.0+",
    icon: Wrench,
    iconBg: "linear-gradient(135deg,#64748b,#0ea5e9)",
    installs: "890K",
    updated: "5 days ago",
    installCmd: "xr skills add toolkit",
    tags: ["slack", "notion", "linear"],
  },
];

export const models = [
  {
    name: "XR Core 1",
    provider: "XR",
    tag: "Flagship",
    context: "1M tokens",
    speed: "Fastest",
    description: "Our in-house agentic model, tuned for tool use and long-horizon tasks.",
    featured: true,
  },
  {
    name: "Claude Opus 4.5",
    provider: "Anthropic",
    tag: "Reasoning",
    context: "2M tokens",
    speed: "Balanced",
    description: "Frontier reasoning for complex planning, code generation, and deep analysis.",
    featured: true,
  },
  {
    name: "GPT-5",
    provider: "OpenAI",
    tag: "General",
    context: "1M tokens",
    speed: "Fast",
    description: "Versatile frontier model with strong generalist performance.",
  },
  {
    name: "Gemini 2.5 Pro",
    provider: "Google",
    tag: "Multimodal",
    context: "1M tokens",
    speed: "Fast",
    description: "Strong multimodal reasoning across text, code, images, and video.",
  },
  {
    name: "DeepSeek V3",
    provider: "DeepSeek",
    tag: "Open-weight",
    context: "128K tokens",
    speed: "Very Fast",
    description: "High-performance open-weight coding model.",
  },
  {
    name: "Llama 4 Maverick",
    provider: "Meta",
    tag: "Open-weight",
    context: "1M tokens",
    speed: "Fast",
    description: "Open-weight model with native multimodal capabilities.",
  },
  {
    name: "Qwen 3 Max",
    provider: "Alibaba",
    tag: "Open-weight",
    context: "1M tokens",
    speed: "Fast",
    description: "Top-tier multilingual open-weight model.",
  },
  {
    name: "Groq Llama 405B",
    provider: "Groq",
    tag: "Ultra-low latency",
    context: "128K tokens",
    speed: "Realtime",
    description: "405B Llama served on Groq's LPU for sub-300ms latency.",
  },
];

export const pricingPlans = [
  {
    name: "Free",
    price: "$0",
    cadence: "forever",
    description: "For individual developers exploring XR.",
    cta: "Get started",
    href: "/downloads",
    featured: false,
    features: [
      "XR CLI + dashboard",
      "Unlimited local runs",
      "Access to free models",
      "Community skills",
      "Public marketplace",
      "Community support",
    ],
  },
  {
    name: "Pro",
    price: "$20",
    cadence: "per user / month",
    description: "For developers who ship with XR daily.",
    cta: "Start Pro trial",
    href: "/downloads",
    featured: true,
    features: [
      "Everything in Free",
      "Pro models (GPT-5, Claude Opus, XR Core)",
      "Priority skill access",
      "Private skills & teams",
      "Advanced MCP servers",
      "Session replay & trace search",
      "Priority support",
    ],
  },
  {
    name: "Team",
    price: "$40",
    cadence: "per user / month",
    description: "For teams collaborating on agents and workflows.",
    cta: "Start Team trial",
    href: "/enterprise",
    featured: false,
    features: [
      "Everything in Pro",
      "SSO / SAML",
      "Shared workspaces",
      "Role-based access",
      "Audit logs (90 days)",
      "Custom model gateways",
      "SLAs & dedicated support",
    ],
  },
  {
    name: "Enterprise",
    price: "Custom",
    cadence: "annual",
    description: "For organizations that need security, scale, and control.",
    cta: "Contact sales",
    href: "/contact",
    featured: false,
    features: [
      "Everything in Team",
      "Self-hosted runtime",
      "VPC deployment",
      "Dedicated models",
      "Custom skills & SLA",
      "SOC 2 / HIPAA / ISO 27001",
      "Dedicated solutions engineer",
    ],
  },
];

export const faqs = [
  {
    q: "Is XR open-source?",
    a: "Yes. The XR runtime, CLI, and most official skills are MIT-licensed. Some cloud-only features ship under a commercial license.",
  },
  {
    q: "Which editors are supported?",
    a: "VS Code, Neovim, JetBrains IDEs, Zed, Cursor, and Windsurf all have first-party extensions. The CLI works anywhere.",
  },
  {
    q: "Can I run XR locally?",
    a: "Absolutely. The runtime is designed for local-first operation with Ollama, Llama.cpp, vLLM, and any OpenAI-compatible endpoint.",
  },
  {
    q: "What is a skill?",
    a: "A skill is a typed, versioned, capability-scoped unit of work — think of it as a better tool. Skills compose into agents.",
  },
  {
    q: "How is XR different from coding agents?",
    a: "Coding agents are one feature of XR. XR is a full runtime: shell, editor, skills, models, security, and deployment in one coherent system.",
  },
  {
    q: "Do you support MCP?",
    a: "Yes. XR is MCP-native — you can use any MCP server without an adapter. We also extend MCP with typed streams and state.",
  },
];

export const changelog = [
  {
    version: "3.1.0",
    date: "July 8, 2026",
    title: "XR 3.1 G — The Agentic Runtime",
    highlights: [
      "Rewritten Rust core: 3x faster cold starts",
      "New skill graph with typed compositions",
      "MCP-native server architecture",
      "Redesigned Dashboard",
      "First-class models marketplace",
      "120+ new official skills",
    ],
  },
  {
    version: "3.0.4",
    date: "June 2, 2026",
    title: "Security & performance patch",
    highlights: [
      "Capability tokens for skills",
      "Improved streaming latency (-18%)",
      "JetBrains extension v2",
      "Support for GPT-5 and Claude Opus 4.5",
    ],
  },
  {
    version: "3.0.0",
    date: "April 14, 2026",
    title: "XR 3.0 — General availability",
    highlights: [
      "Stable runtime API",
      "Marketplace with 8,000 skills",
      "Enterprise SSO",
      "SOC 2 Type II certified",
    ],
  },
];

export const posts = [
  {
    slug: "xr-3-1-ga",
    title: "XR 3.1 is generally available",
    excerpt:
      "Today we're releasing XR 3.1 G — a complete rewrite of the agentic runtime that is 3x faster, more secure, and ships with a new skill graph.",
    author: "The XR Team",
    date: "July 8, 2026",
    tag: "Release",
    readTime: "6 min read",
  },
  {
    slug: "skill-graph",
    title: "Designing the XR skill graph",
    excerpt:
      "Skills are the primitive of agentic software. Here's how we designed a typed, composable graph that scales to 12,000+ skills.",
    author: "Engineering",
    date: "June 22, 2026",
    tag: "Engineering",
    readTime: "12 min read",
  },
  {
    slug: "security-model",
    title: "XR's capability-based security model",
    excerpt:
      "How we think about agent security, from sandboxing to human-in-the-loop confirmations, signed skills, and audit trails.",
    author: "Security",
    date: "May 30, 2026",
    tag: "Security",
    readTime: "9 min read",
  },
  {
    slug: "local-first",
    title: "Local-first agents with Ollama",
    excerpt:
      "A guide to running XR entirely offline with open-weight models — no cloud, no telemetry, no keys.",
    author: "DX",
    date: "May 12, 2026",
    tag: "Tutorial",
    readTime: "7 min read",
  },
];

export const research = [
  {
    title: "Skill Memory: Episodic Retrieval for Long-Horizon Agents",
    authors: "XR Research",
    year: 2026,
    tag: "Agents",
  },
  {
    title: "Typed Tool Use: Why Agents Need Schemas That Don't Lie",
    authors: "XR Research",
    year: 2026,
    tag: "Systems",
  },
  {
    title: "Streaming Interleaved Thought & Action at 100k tok/s",
    authors: "XR Research",
    year: 2025,
    tag: "Inference",
  },
  {
    title: "Capability-Based Security for LLM Executables",
    authors: "XR Research",
    year: 2025,
    tag: "Security",
  },
];
