/* eslint-disable */
/**
 * GENERATED FILE — do not edit by hand.
 * Source: skills/* and plugins/* — the real bundled inventory.
 * Regenerate: bun run website/scripts/generate-marketplace.ts
 * CI fails on drift: add `website:marketplace:check` to the gates.
 *
 * No fabricated popularity metrics. Bundled items report
 * downloads=0, rating=0, reviews=0 and are labeled "Bundled with XR"
 * (Constitution Art. XV.4 — marketplace trust is never popularity).
 */
import { Code2, Terminal, Database, Palette, Workflow, BookOpen, FileCode2, ShieldCheck, Globe, Rocket, Zap } from "lucide-react";
import type { ComponentType } from "react";

export type ItemType = "skill" | "extension";

export interface MarketplaceItem {
  id: string;
  name: string;
  tagline: string;
  description: string;
  type: ItemType;
  category: string;
  author: string;
  verified: boolean;
  downloads: number;
  rating: number;
  reviews: number;
  version: string;
  compatibility: string;
  icon: ComponentType<{ className?: string }>;
  iconBg: string;
  installs: string;
  updated: string;
  installCmd: string;
  tags: string[];
}

export const marketplaceCategories = [
  { id: "all", label: "All" },
  { id: "coding", label: "Coding" },
  { id: "devops", label: "DevOps" },
  { id: "data", label: "Data" },
  { id: "design", label: "Design" },
  { id: "productivity", label: "Productivity" },
  { id: "research", label: "Research" },
  { id: "writing", label: "Writing" },
  { id: "security", label: "Security" },
  { id: "web", label: "Web" },
] as const;

export const marketplaceItems: MarketplaceItem[] = [
  {
    id: "academic_research",
    name: "Academic Research",
    tagline: "Academic Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and c…",
    description: "Academic Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and clear conclusions.",
    type: "skill",
    category: "research",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: BookOpen,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect academic_research",
    tags: ["academic","literature","citations"],
  },
  {
    id: "api_design",
    name: "Api Design",
    tagline: "Api Design — bundled XR skill.",
    description: "Api Design — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect api_design",
    tags: [],
  },
  {
    id: "architecture_reviewer",
    name: "Architecture Reviewer",
    tagline: "Architecture Reviewer delivers production-grade technical work with clear architecture, tests, maintainabilit…",
    description: "Architecture Reviewer delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect architecture_reviewer",
    tags: ["architecture","review","systems"],
  },
  {
    id: "brand_designer",
    name: "Brand Designer",
    tagline: "Brand Designer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and ex…",
    description: "Brand Designer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#8b5cf6,#ec4899)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect brand_designer",
    tags: ["brand","identity","voice"],
  },
  {
    id: "code_auditor",
    name: "Code Auditor",
    tagline: "Code Auditor delivers defensive, authorized, auditable security analysis with explicit scope boundaries and r…",
    description: "Code Auditor delivers defensive, authorized, auditable security analysis with explicit scope boundaries and risk handling.",
    type: "skill",
    category: "security",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: ShieldCheck,
    iconBg: "linear-gradient(135deg,#f472b6,#f59e0b)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect code_auditor",
    tags: ["code-audit","secure-code","review"],
  },
  {
    id: "competitive_intelligence",
    name: "Competitive Intelligence",
    tagline: "Competitive Intelligence delivers source-aware research synthesis with evidence grading, uncertainty tracking…",
    description: "Competitive Intelligence delivers source-aware research synthesis with evidence grading, uncertainty tracking, and clear conclusions.",
    type: "skill",
    category: "research",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: BookOpen,
    iconBg: "linear-gradient(135deg,#14b8a6,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect competitive_intelligence",
    tags: ["competitors","positioning","pricing"],
  },
  {
    id: "content_creator",
    name: "Content Creator",
    tagline: "Content Creator delivers distinctive creative work grounded in audience, constraints, taste, iteration, and e…",
    description: "Content Creator delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#ef4444,#f97316)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect content_creator",
    tags: ["content","calendar","audience"],
  },
  {
    id: "copywriter",
    name: "Copywriter",
    tagline: "Copywriter delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execut…",
    description: "Copywriter delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#ec4899,#a855f7)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect copywriter",
    tags: ["copy","conversion","voice"],
  },
  {
    id: "crm_assistant",
    name: "CRM Assistant",
    tagline: "CRM Assistant delivers practical business output with market context, metrics, stakeholder clarity, and execu…",
    description: "CRM Assistant delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect crm_assistant",
    tags: ["crm","customer","pipeline"],
  },
  {
    id: "customer_support",
    name: "Customer Support",
    tagline: "Customer Support delivers practical business output with market context, metrics, stakeholder clarity, and ex…",
    description: "Customer Support delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect customer_support",
    tags: ["support","ticket","customer"],
  },
  {
    id: "daily-brief",
    name: "Daily Brief",
    tagline: "Daily Brief — bundled XR skill.",
    description: "Daily Brief — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect daily-brief",
    tags: [],
  },
  {
    id: "db_migrate",
    name: "Db Migrate",
    tagline: "Db Migrate — bundled XR skill.",
    description: "Db Migrate — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#8b5cf6,#ec4899)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect db_migrate",
    tags: [],
  },
  {
    id: "debug_error",
    name: "Debug Error",
    tagline: "Debug Error — bundled XR skill.",
    description: "Debug Error — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#f472b6,#f59e0b)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect debug_error",
    tags: [],
  },
  {
    id: "debugging_expert",
    name: "Debugging Expert",
    tagline: "Debugging Expert delivers production-grade technical work with clear architecture, tests, maintainability, an…",
    description: "Debugging Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#14b8a6,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect debugging_expert",
    tags: ["debugging","root-cause","observability"],
  },
  {
    id: "deep_research",
    name: "Deep Research",
    tagline: "Deep Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and clear…",
    description: "Deep Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and clear conclusions.",
    type: "skill",
    category: "research",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: BookOpen,
    iconBg: "linear-gradient(135deg,#ef4444,#f97316)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect deep_research",
    tags: ["research","synthesis","sources"],
  },
  {
    id: "devops_engineer",
    name: "DevOps Engineer",
    tagline: "DevOps Engineer delivers production-grade technical work with clear architecture, tests, maintainability, and…",
    description: "DevOps Engineer delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#ec4899,#a855f7)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect devops_engineer",
    tags: ["ci-cd","infra","observability"],
  },
  {
    id: "docker_expert",
    name: "Docker Expert",
    tagline: "Docker Expert delivers production-grade technical work with clear architecture, tests, maintainability, and o…",
    description: "Docker Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect docker_expert",
    tags: ["docker","containers","deployment"],
  },
  {
    id: "email_writer",
    name: "Email Writer",
    tagline: "Email Writer delivers practical business output with market context, metrics, stakeholder clarity, and execut…",
    description: "Email Writer delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect email_writer",
    tags: ["email","communication","copy"],
  },
  {
    id: "explain_codebase",
    name: "Explain Codebase",
    tagline: "Explain Codebase — bundled XR skill.",
    description: "Explain Codebase — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect explain_codebase",
    tags: [],
  },
  {
    id: "financial_analyst",
    name: "Financial Analyst",
    tagline: "Financial Analyst delivers practical business output with market context, metrics, stakeholder clarity, and e…",
    description: "Financial Analyst delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#8b5cf6,#ec4899)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect financial_analyst",
    tags: ["finance","modeling","metrics"],
  },
  {
    id: "full_stack_engineer",
    name: "Full Stack Engineer",
    tagline: "Full Stack Engineer delivers production-grade technical work with clear architecture, tests, maintainability,…",
    description: "Full Stack Engineer delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#f472b6,#f59e0b)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect full_stack_engineer",
    tags: ["architecture","frontend","backend"],
  },
  {
    id: "generate_readme",
    name: "Generate Readme",
    tagline: "Generate Readme — bundled XR skill.",
    description: "Generate Readme — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#14b8a6,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect generate_readme",
    tags: [],
  },
  {
    id: "git_commit_message",
    name: "Git Commit Message",
    tagline: "Git Commit Message — bundled XR skill.",
    description: "Git Commit Message — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#ef4444,#f97316)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect git_commit_message",
    tags: [],
  },
  {
    id: "git_expert",
    name: "Git Expert",
    tagline: "Git Expert delivers production-grade technical work with clear architecture, tests, maintainability, and oper…",
    description: "Git Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#ec4899,#a855f7)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect git_expert",
    tags: ["git","branching","history"],
  },
  {
    id: "github",
    name: "GitHub",
    tagline: "Reference integration plugin: look up public GitHub repositories through permissioned network access and opti…",
    description: "Reference integration plugin: look up public GitHub repositories through permissioned network access and optional named secrets.",
    type: "extension",
    category: "devops",
    author: "rrrtx",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: ">=1.0.0 <2.0.0",
    icon: Rocket,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills install-local github",
    tags: [],
  },
  {
    id: "go_expert",
    name: "Go Expert",
    tagline: "Go Expert delivers production-grade technical work with clear architecture, tests, maintainability, and opera…",
    description: "Go Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect go_expert",
    tags: ["go","services","concurrency"],
  },
  {
    id: "hello",
    name: "Hello XR",
    tagline: "Reference plugin: contributes a command and a safe echo tool.",
    description: "Reference plugin: contributes a command and a safe echo tool. Demonstrates the XR Stage 10 plugin contract with zero sensitive permissions.",
    type: "extension",
    category: "devops",
    author: "rrrtx",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: ">=1.0.0 <2.0.0",
    icon: Rocket,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills install-local hello",
    tags: [],
  },
  {
    id: "incident_response",
    name: "Incident Response",
    tagline: "Incident Response delivers defensive, authorized, auditable security analysis with explicit scope boundaries …",
    description: "Incident Response delivers defensive, authorized, auditable security analysis with explicit scope boundaries and risk handling.",
    type: "skill",
    category: "security",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: ShieldCheck,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect incident_response",
    tags: ["incident","forensics","containment"],
  },
  {
    id: "java_expert",
    name: "Java Expert",
    tagline: "Java Expert delivers production-grade technical work with clear architecture, tests, maintainability, and ope…",
    description: "Java Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect java_expert",
    tags: ["java","spring","enterprise"],
  },
  {
    id: "kubernetes_expert",
    name: "Kubernetes Expert",
    tagline: "Kubernetes Expert delivers production-grade technical work with clear architecture, tests, maintainability, a…",
    description: "Kubernetes Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#8b5cf6,#ec4899)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect kubernetes_expert",
    tags: ["kubernetes","cluster","helm"],
  },
  {
    id: "logo_designer",
    name: "Logo Designer",
    tagline: "Logo Designer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and exe…",
    description: "Logo Designer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#f472b6,#f59e0b)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect logo_designer",
    tags: ["logo","identity","brand"],
  },
  {
    id: "malware_analyst",
    name: "Malware Analyst",
    tagline: "Malware Analyst delivers defensive, authorized, auditable security analysis with explicit scope boundaries an…",
    description: "Malware Analyst delivers defensive, authorized, auditable security analysis with explicit scope boundaries and risk handling.",
    type: "skill",
    category: "security",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: ShieldCheck,
    iconBg: "linear-gradient(135deg,#14b8a6,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect malware_analyst",
    tags: ["malware","reverse-engineering","ioc"],
  },
  {
    id: "market_research",
    name: "Market Research",
    tagline: "Market Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and cle…",
    description: "Market Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and clear conclusions.",
    type: "skill",
    category: "research",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: BookOpen,
    iconBg: "linear-gradient(135deg,#ef4444,#f97316)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect market_research",
    tags: ["market","customers","segments"],
  },
  {
    id: "marketing_strategist",
    name: "Marketing Strategist",
    tagline: "Marketing Strategist delivers practical business output with market context, metrics, stakeholder clarity, an…",
    description: "Marketing Strategist delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#ec4899,#a855f7)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect marketing_strategist",
    tags: ["marketing","positioning","campaigns"],
  },
  {
    id: "negotiation_expert",
    name: "Negotiation Expert",
    tagline: "Negotiation Expert delivers practical business output with market context, metrics, stakeholder clarity, and …",
    description: "Negotiation Expert delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect negotiation_expert",
    tags: ["negotiation","deals","pricing"],
  },
  {
    id: "nextjs_expert",
    name: "Next.js Expert",
    tagline: "Next.js Expert delivers production-grade technical work with clear architecture, tests, maintainability, and …",
    description: "Next.js Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect nextjs_expert",
    tags: ["nextjs","app-router","vercel"],
  },
  {
    id: "node_expert",
    name: "Node Expert",
    tagline: "Node Expert delivers production-grade technical work with clear architecture, tests, maintainability, and ope…",
    description: "Node Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect node_expert",
    tags: ["node","api","typescript"],
  },
  {
    id: "osint_researcher",
    name: "OSINT Researcher",
    tagline: "OSINT Researcher delivers defensive, authorized, auditable security analysis with explicit scope boundaries a…",
    description: "OSINT Researcher delivers defensive, authorized, auditable security analysis with explicit scope boundaries and risk handling.",
    type: "skill",
    category: "security",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: ShieldCheck,
    iconBg: "linear-gradient(135deg,#8b5cf6,#ec4899)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect osint_researcher",
    tags: ["osint","investigation","sources"],
  },
  {
    id: "paper_analyzer",
    name: "Paper Analyzer",
    tagline: "Paper Analyzer delivers source-aware research synthesis with evidence grading, uncertainty tracking, and clea…",
    description: "Paper Analyzer delivers source-aware research synthesis with evidence grading, uncertainty tracking, and clear conclusions.",
    type: "skill",
    category: "research",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: BookOpen,
    iconBg: "linear-gradient(135deg,#f472b6,#f59e0b)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect paper_analyzer",
    tags: ["papers","methods","results"],
  },
  {
    id: "patent_research",
    name: "Patent Research",
    tagline: "Patent Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and cle…",
    description: "Patent Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and clear conclusions.",
    type: "skill",
    category: "research",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: BookOpen,
    iconBg: "linear-gradient(135deg,#14b8a6,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect patent_research",
    tags: ["patents","prior-art","claims"],
  },
  {
    id: "pentest_assistant",
    name: "Pentest Assistant",
    tagline: "Pentest Assistant delivers defensive, authorized, auditable security analysis with explicit scope boundaries …",
    description: "Pentest Assistant delivers defensive, authorized, auditable security analysis with explicit scope boundaries and risk handling.",
    type: "skill",
    category: "security",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: ShieldCheck,
    iconBg: "linear-gradient(135deg,#ef4444,#f97316)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect pentest_assistant",
    tags: ["pentest","authorized","vulnerability"],
  },
  {
    id: "performance_optimizer",
    name: "Performance Optimizer",
    tagline: "Performance Optimizer delivers production-grade technical work with clear architecture, tests, maintainabilit…",
    description: "Performance Optimizer delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#ec4899,#a855f7)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect performance_optimizer",
    tags: ["performance","profiling","latency"],
  },
  {
    id: "pr_description",
    name: "Pr Description",
    tagline: "Pr Description — bundled XR skill.",
    description: "Pr Description — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect pr_description",
    tags: [],
  },
  {
    id: "presentation_builder",
    name: "Presentation Builder",
    tagline: "Presentation Builder delivers distinctive creative work grounded in audience, constraints, taste, iteration, …",
    description: "Presentation Builder delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect presentation_builder",
    tags: ["slides","presentation","story"],
  },
  {
    id: "privacy_advisor",
    name: "Privacy Advisor",
    tagline: "Privacy Advisor delivers defensive, authorized, auditable security analysis with explicit scope boundaries an…",
    description: "Privacy Advisor delivers defensive, authorized, auditable security analysis with explicit scope boundaries and risk handling.",
    type: "skill",
    category: "security",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: ShieldCheck,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect privacy_advisor",
    tags: ["privacy","data-protection","policy"],
  },
  {
    id: "product_manager",
    name: "Product Manager",
    tagline: "Product Manager delivers practical business output with market context, metrics, stakeholder clarity, and exe…",
    description: "Product Manager delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#8b5cf6,#ec4899)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect product_manager",
    tags: ["product","roadmap","requirements"],
  },
  {
    id: "project_manager",
    name: "Project Manager",
    tagline: "Project Manager delivers practical business output with market context, metrics, stakeholder clarity, and exe…",
    description: "Project Manager delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#f472b6,#f59e0b)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect project_manager",
    tags: ["project","planning","risk"],
  },
  {
    id: "proposal_writer",
    name: "Proposal Writer",
    tagline: "Proposal Writer delivers practical business output with market context, metrics, stakeholder clarity, and exe…",
    description: "Proposal Writer delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#14b8a6,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect proposal_writer",
    tags: ["proposal","rfp","sales"],
  },
  {
    id: "python_expert",
    name: "Python Expert",
    tagline: "Python Expert delivers production-grade technical work with clear architecture, tests, maintainability, and o…",
    description: "Python Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#ef4444,#f97316)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect python_expert",
    tags: ["python","automation","data"],
  },
  {
    id: "react_expert",
    name: "React Expert",
    tagline: "React Expert delivers production-grade technical work with clear architecture, tests, maintainability, and op…",
    description: "React Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#ec4899,#a855f7)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect react_expert",
    tags: ["react","components","state"],
  },
  {
    id: "refactor_clean",
    name: "Refactor Clean",
    tagline: "Refactor Clean — bundled XR skill.",
    description: "Refactor Clean — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect refactor_clean",
    tags: [],
  },
  {
    id: "refactoring_expert",
    name: "Refactoring Expert",
    tagline: "Refactoring Expert delivers production-grade technical work with clear architecture, tests, maintainability, …",
    description: "Refactoring Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect refactoring_expert",
    tags: ["refactor","clean-code","maintainability"],
  },
  {
    id: "rust_expert",
    name: "Rust Expert",
    tagline: "Rust Expert delivers production-grade technical work with clear architecture, tests, maintainability, and ope…",
    description: "Rust Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect rust_expert",
    tags: ["rust","systems","performance"],
  },
  {
    id: "sales_agent",
    name: "Sales Agent",
    tagline: "Sales Agent delivers practical business output with market context, metrics, stakeholder clarity, and executi…",
    description: "Sales Agent delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#8b5cf6,#ec4899)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect sales_agent",
    tags: ["sales","pipeline","outreach"],
  },
  {
    id: "scientific_research",
    name: "Scientific Research",
    tagline: "Scientific Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and…",
    description: "Scientific Research delivers source-aware research synthesis with evidence grading, uncertainty tracking, and clear conclusions.",
    type: "skill",
    category: "research",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: BookOpen,
    iconBg: "linear-gradient(135deg,#f472b6,#f59e0b)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect scientific_research",
    tags: ["science","hypothesis","evidence"],
  },
  {
    id: "security_audit",
    name: "Security Audit",
    tagline: "Security Audit — bundled XR skill.",
    description: "Security Audit — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#14b8a6,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect security_audit",
    tags: [],
  },
  {
    id: "seo_expert",
    name: "SEO Expert",
    tagline: "SEO Expert delivers practical business output with market context, metrics, stakeholder clarity, and executio…",
    description: "SEO Expert delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#ef4444,#f97316)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect seo_expert",
    tags: ["seo","content","technical-seo"],
  },
  {
    id: "soc_analyst",
    name: "SOC Analyst",
    tagline: "SOC Analyst delivers defensive, authorized, auditable security analysis with explicit scope boundaries and ri…",
    description: "SOC Analyst delivers defensive, authorized, auditable security analysis with explicit scope boundaries and risk handling.",
    type: "skill",
    category: "security",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: ShieldCheck,
    iconBg: "linear-gradient(135deg,#ec4899,#a855f7)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect soc_analyst",
    tags: ["soc","alerts","siem"],
  },
  {
    id: "social_media_creator",
    name: "Social Media Creator",
    tagline: "Social Media Creator delivers distinctive creative work grounded in audience, constraints, taste, iteration, …",
    description: "Social Media Creator delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect social_media_creator",
    tags: ["social","posts","platforms"],
  },
  {
    id: "startup_advisor",
    name: "Startup Advisor",
    tagline: "Startup Advisor delivers practical business output with market context, metrics, stakeholder clarity, and exe…",
    description: "Startup Advisor delivers practical business output with market context, metrics, stakeholder clarity, and execution focus.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#22d3ee,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect startup_advisor",
    tags: ["startup","strategy","fundraising"],
  },
  {
    id: "story_writer",
    name: "Story Writer",
    tagline: "Story Writer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and exec…",
    description: "Story Writer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#10b981,#06b6d4)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect story_writer",
    tags: ["story","narrative","characters"],
  },
  {
    id: "testing_expert",
    name: "Testing Expert",
    tagline: "Testing Expert delivers production-grade technical work with clear architecture, tests, maintainability, and …",
    description: "Testing Expert delivers production-grade technical work with clear architecture, tests, maintainability, and operational awareness.",
    type: "skill",
    category: "coding",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Code2,
    iconBg: "linear-gradient(135deg,#8b5cf6,#ec4899)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect testing_expert",
    tags: ["tests","qa","coverage"],
  },
  {
    id: "threat_hunter",
    name: "Threat Hunter",
    tagline: "Threat Hunter delivers defensive, authorized, auditable security analysis with explicit scope boundaries and …",
    description: "Threat Hunter delivers defensive, authorized, auditable security analysis with explicit scope boundaries and risk handling.",
    type: "skill",
    category: "security",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: ShieldCheck,
    iconBg: "linear-gradient(135deg,#f472b6,#f59e0b)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect threat_hunter",
    tags: ["threat-hunting","detection","logs"],
  },
  {
    id: "ui_designer",
    name: "UI Designer",
    tagline: "UI Designer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execu…",
    description: "UI Designer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#14b8a6,#6366f1)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect ui_designer",
    tags: ["ui","visual-design","interfaces"],
  },
  {
    id: "ux_designer",
    name: "UX Designer",
    tagline: "UX Designer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execu…",
    description: "UX Designer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#ef4444,#f97316)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect ux_designer",
    tags: ["ux","research","flows"],
  },
  {
    id: "video_script_writer",
    name: "Video Script Writer",
    tagline: "Video Script Writer delivers distinctive creative work grounded in audience, constraints, taste, iteration, a…",
    description: "Video Script Writer delivers distinctive creative work grounded in audience, constraints, taste, iteration, and execution quality.",
    type: "skill",
    category: "design",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1.0.0",
    compatibility: "Bundled with XR",
    icon: Palette,
    iconBg: "linear-gradient(135deg,#ec4899,#a855f7)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect video_script_writer",
    tags: ["video","script","storyboard"],
  },
  {
    id: "write_tests",
    name: "Write Tests",
    tagline: "Write Tests — bundled XR skill.",
    description: "Write Tests — bundled XR skill.",
    type: "skill",
    category: "productivity",
    author: "XR Official",
    verified: true,
    downloads: 0,
    rating: 0,
    reviews: 0,
    version: "1",
    compatibility: "Bundled with XR",
    icon: Workflow,
    iconBg: "linear-gradient(135deg,#7c5cff,#3b82f6)",
    installs: "Bundled",
    updated: "Ships with XR",
    installCmd: "xr skills inspect write_tests",
    tags: [],
  },
];
