export const site = {
  name: "XR",
  tagline: "The Agentic Runtime for Software",
  description:
    "XR is an open-source agentic runtime that turns your terminal, editor, and workflow into an AI-native development environment. Build, extend, and ship with 12,000+ skills and models.",
  url: "https://xr.dev",
  twitter: "@xr_runtime",
  github: "https://github.com/xr-dev/xr",
  npm: "https://www.npmjs.com/package/@xr/agent",
  installCmd: "npm i -g @xr/agent && xr",
  version: "3.1.0",
  nav: [
    { label: "Features", href: "/features" },
    { label: "Marketplace", href: "/marketplace" },
    { label: "Models", href: "/models" },
    { label: "Enterprise", href: "/enterprise" },
    { label: "Pricing", href: "/pricing" },
    { label: "Docs", href: "/docs" },
    { label: "Blog", href: "/blog" },
  ],
  footer: {
    product: [
      { label: "Features", href: "/features" },
      { label: "Marketplace", href: "/marketplace" },
      { label: "Skills", href: "/marketplace?tab=skills" },
      { label: "Extensions", href: "/marketplace?tab=extensions" },
      { label: "Models", href: "/models" },
      { label: "Downloads", href: "/downloads" },
      { label: "Changelog", href: "/changelog" },
      { label: "Roadmap", href: "/roadmap" },
    ],
    resources: [
      { label: "Documentation", href: "/docs" },
      { label: "Research", href: "/research" },
      { label: "Blog", href: "/blog" },
      { label: "Community", href: "/community" },
      { label: "Support", href: "/support" },
      { label: "Status", href: "/status" },
      { label: "Contact", href: "/contact" },
    ],
    company: [
      { label: "About", href: "/about" },
      { label: "Careers", href: "/careers" },
      { label: "Enterprise", href: "/enterprise" },
      { label: "Security", href: "/security" },
      { label: "Press", href: "/about#press" },
      { label: "Partners", href: "/enterprise#partners" },
    ],
    legal: [
      { label: "Privacy", href: "/privacy" },
      { label: "Terms", href: "/terms" },
    ],
  },
};
