#!/usr/bin/env bun
/**
 * XR Phase 9 · T2 — release-note generator (conventional commits).
 *
 *   bun run scripts/changelog.ts                 # last tag..HEAD, human output
 *   bun run scripts/changelog.ts --from v7.0.0 --to v7.1.0 --version 7.1.0
 *
 * XR's git history is already conventional (`feat(scope): …`, `fix(scope): …`,
 * `docs(scope): …`, merge commits for PRs). This generator groups a tag range
 * into typed sections and produces GitHub-release body markdown — replacing
 * the unstructured auto-generated blob with reviewable release notes.
 *
 * Principles (research R2): the same script runs inside the release workflow
 * (its output *is* the release body) and locally; commit subjects are the
 * input, git is the only store, and the output is deterministic for a given
 * range — regenerating release notes for an old tag always yields the same
 * text. An empty range produces an explicit marker, never silent emptiness.
 *
 * Conventions: docs/release/CHANGELOG-CONVENTION.md.
 */

import { spawnSync } from "node:child_process";

export interface ParsedCommit {
  type: string;
  scope: string | null;
  subject: string;
  hash: string;
  breaking: boolean;
}

const TYPE_LABELS: Array<[string, string]> = [
  ["feat", "Added"],
  ["fix", "Fixed"],
  ["perf", "Performance"],
  ["refactor", "Refactored"],
  ["docs", "Documentation"],
  ["test", "Tests"],
  ["build", "Build & distribution"],
  ["ci", "CI"],
  ["chore", "Chore"],
  ["style", "Style"],
  ["revert", "Reverts"],
];

const ORDER = new Map(TYPE_LABELS.map(([t], i) => [t, i]));

export function parseCommitLine(line: string): ParsedCommit | null {
  const m = line.match(/^([0-9a-f]{7,40}) ([^\s(]+)(\(([^)]*)\))?(!)?: (.+)$/);
  if (!m) return null;
  const type = m[2]!.toLowerCase();
  if (!ORDER.has(type)) return null;
  return { hash: m[1]!, type, scope: m[4] ?? null, subject: m[6]!, breaking: m[5] === "!" };
}

/** `git log` subjects for a range; merge commits excluded (PRs land as squash or merge+commits). */
export function commitsInRange(from: string, to: string, cwd: string = process.cwd()): ParsedCommit[] {
  const range = from ? `${from}..${to}` : to;
  const r = spawnSync("git", ["log", "--format=%H%x02%s", "--no-merges", range], {
    cwd,
    encoding: "utf8",
    timeout: 60_000,
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (r.status !== 0) {
    throw new Error(`git log ${range} failed: ${(r.stderr ?? "").trim()}`);
  }
  const commits: ParsedCommit[] = [];
  for (const raw of r.stdout.split("\n")) {
    if (!raw.trim()) continue;
    const [hash, ...rest] = raw.split("\x02");
    const p = parseCommitLine(`${hash!.slice(0, 12)} ${rest.join("\x02")}`);
    if (p) commits.push(p);
  }
  return commits;
}

/** Resolve the most recent tag before HEAD that looks like a stable release. */
export function previousStableTag(cwd: string = process.cwd()): string | null {
  const r = spawnSync("git", ["tag", "--sort=-v:refname", "--list", "v*"], {
    cwd,
    encoding: "utf8",
    timeout: 30_000,
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (r.status !== 0) return null;
  const stable = r.stdout
    .split("\n")
    .map((t) => t.trim())
    .filter((t) => /^v\d+\.\d+\.\d+$/.test(t));
  return stable[0] ?? null;
}

export interface ChangelogSection {
  label: string;
  items: string[];
}

export function renderChangelog(opts: {
  version: string;
  date: string;
  commits: ParsedCommit[];
  fromRef?: string;
  toRef?: string;
}): string {
  const { version, date, commits } = opts;
  const rangeNote = opts.fromRef && opts.toRef
    ? `\n<sub>Range: \`${opts.fromRef}…${opts.toRef}\` · generated by scripts/changelog.ts (deterministic for this range).</sub>\n`
    : "";
  if (commits.length === 0) {
    return `## ${version} — ${date}\n${rangeNote}\n_No user-facing changes in this range._\n`;
  }
  const breaking = commits.filter((c) => c.breaking);
  const sections: ChangelogSection[] = [];
  for (const [type, label] of TYPE_LABELS) {
    const items = commits.filter((c) => c.type === type);
    if (items.length === 0) continue;
    sections.push({
      label,
      items: items.map((c) => `- ${c.scope ? `**${c.scope}:** ` : ""}${c.subject} (\`${c.hash.slice(0, 7)}\`)`),
    });
  }
  const parts: string[] = [`## ${version} — ${date}\n${rangeNote}`];
  if (breaking.length > 0) {
    parts.push(`### ⚠ Breaking changes\n\n${breaking.map((c) => `- ${c.scope ? `**${c.scope}:** ` : ""}${c.subject} (\`${c.hash.slice(0, 7)}\`)`).join("\n")}\n`);
  }
  for (const s of sections) {
    parts.push(`### ${s.label}\n\n${s.items.join("\n")}\n`);
  }
  return parts.join("\n");
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const get = (flag: string) => {
    const i = argv.indexOf(flag);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  const to = get("--to") ?? "HEAD";
  const from = get("--from") ?? previousStableTag() ?? "";
  const date = get("--date") ?? new Date().toISOString().slice(0, 10);
  const commits = commitsInRange(from, to);
  const defaultVersion = to.startsWith("v") ? to.slice(1) : "(unreleased)";
  const version = get("--version") ?? defaultVersion;
  process.stdout.write(renderChangelog({ version, date, commits, fromRef: from || undefined, toRef: to }) + "\n");
}

if (import.meta.main) {
  main().catch((err) => {
    console.error("[changelog] fatal:", err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}
