#!/usr/bin/env bun
/**
 * XR Phase 9 · T3 — one canonical build, many channels (Art. XXII).
 *
 * THE single authority for native package-manager channel definitions. Every
 * channel file is GENERATED from the release manifest; never hand-edited
 * (same law as release:stamp — the generator is the source of truth).
 *
 * Channels (validated install surfaces; "supported" means install-tested):
 *   github     per-target binaries + SHA256SUMS (default distribution)
 *   homebrew   packaging/homebrew/xr.rb     (macOS arm64/x64 · Linux x64/arm64)
 *   winget     packaging/winget/…           (windows-x64 zip, portable)
 *   scoop      packaging/scoop/xr.json      (windows-x64 zip)
 *   deb        xr_<version>_amd64.deb       (built at release; see build-deb.ts)
 *   npm        OIDC trusted publishing        (release.yml publish-npm)
 *   docker     GHCR image + cosign signature  (release.yml docker-push)
 *
 * Modes:
 *   --write     regenerate packaging/* templates (contributor flow)
 *   --check     drift gate: packaging/* must equal generated templates
 *               (fails closed — used by `bun run ci` and the release gate)
 *   --stamp --sums dist/SHA256SUMS --out dist/channels
 *               produce the PUBLISHABLE channel set: every sha256 filled from
 *               the release's signed checksums. Fails closed if any required
 *               artifact is missing from the sums (channel-bundle completeness).
 *
 * Repo templates contain NO checksums (checksums exist only after the build).
 * The release pipeline stamps them from SHA256SUMS so every channel points at
 * the same canonical bytes — a channel cannot drift from what was signed.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import {
  ROOT,
  loadManifest,
  type ReleaseManifest,
} from "./release-manifest.ts";
import { parse } from "./sums.ts";

export const PACKAGING_DIR = join(ROOT, "packaging");

// ── Canonical per-target release assets ────────────────────────────────────

export interface ReleaseAsset {
  /** Key used for stamping lookup into SHA256SUMS. */
  file: string;
  target: string;
}

export const BINARY_ASSETS: ReleaseAsset[] = [
  { file: "xr-linux-x64", target: "linux-x64" },
  { file: "xr-linux-arm64", target: "linux-arm64" },
  { file: "xr-darwin-arm64", target: "darwin-arm64" },
  { file: "xr-darwin-x64", target: "darwin-x64" },
  { file: "xr-windows-x64.exe", target: "windows-x64" },
];

/** Extra channel-facing artifacts built in the release job. */
export const CHANNEL_ASSETS: ReleaseAsset[] = [
  { file: "xr-windows-x64.zip", target: "windows-x64" }, // winget + scoop
  { file: "xr_VERSION_amd64.deb", target: "linux-x64" }, // apt (version placeholder)
];

export function downloadUrl(manifest: ReleaseManifest, file: string): string {
  const { repo, version } = manifest.identity;
  return `${repo}/releases/download/v${version}/${file}`;
}

// ── Homebrew formula ───────────────────────────────────────────────────────

export function renderHomebrewFormula(manifest: ReleaseManifest, sums?: Map<string, string>): string {
  const id = manifest.identity;
  const sha = (key: string): string => {
    const s = sums?.get(key);
    return sums ? requireSha(s, key) : `SHA256_${key.replace(/[^A-Za-z0-9]/g, "_").toUpperCase()}`;
  };
  return `# XR — Homebrew formula (Phase 9 · T3)
# GENERATED by scripts/channel-manifest.ts from release.manifest.json — do not edit.
# Checksums are stamped from the release's signed SHA256SUMS at release time.
class Xr < Formula
  desc "${id.description}"
  homepage "${id.repo}"
  version "${id.version}"
  license "${id.license}"

  on_macos do
    on_arm do
      url "${downloadUrl(manifest, "xr-darwin-arm64")}"
      sha256 "${sha("xr-darwin-arm64")}"
    end
    on_intel do
      url "${downloadUrl(manifest, "xr-darwin-x64")}"
      sha256 "${sha("xr-darwin-x64")}"
    end
  end

  on_linux do
    on_arm do
      url "${downloadUrl(manifest, "xr-linux-arm64")}"
      sha256 "${sha("xr-linux-arm64")}"
    end
    on_intel do
      url "${downloadUrl(manifest, "xr-linux-x64")}"
      sha256 "${sha("xr-linux-x64")}"
    end
  end

  def install
    binary = Dir["xr-*"].first
    bin.install binary => "xr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/xr --version")
  end
end
`;
}

// ── WinGet manifests (portable installer over xr-windows-x64.zip) ─────────

export interface RenderedChannelFile {
  /** Path relative to the repo root (template mode) or to the output dir (stamp mode). */
  relpath: string;
  content: string;
}

const STAMP_GUARD = "STAMPED-FROM-SIGNED-SHA256SUMS";

export function renderWinget(manifest: ReleaseManifest, sums?: Map<string, string>): RenderedChannelFile[] {
  const id = manifest.identity;
  const version = id.version;
  const publisher = "ahmadrrrtx";
  const packageId = `${publisher}.XR`;
  const zipUrl = downloadUrl(manifest, "xr-windows-x64.zip");
  const sha = sums ? requireSha(sums.get("xr-windows-x64.zip"), "xr-windows-x64.zip") : "SHA256_XR_WINDOWS_X64_ZIP";
  const base = `winget/manifests/r/${publisher}/XR/${version}`;
  return [
    {
      relpath: `${base}/${packageId}.yaml`,
      content: `# GENERATED by scripts/channel-manifest.ts — do not edit by hand.
PackageIdentifier: ${packageId}
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
`,
    },
    {
      relpath: `${base}/${packageId}.locale.en-US.yaml`,
      content: `# GENERATED by scripts/channel-manifest.ts — do not edit by hand.
PackageIdentifier: ${packageId}
PackageVersion: ${version}
PackageLocale: en-US
Publisher: ${id.author}
PackageName: XR
PackageUrl: ${id.repo}
License: ${id.license}
LicenseUrl: ${id.repo}/blob/main/LICENSE
ShortDescription: ${id.description.split(".")[0]}.
Tags:
  - ai
  - cli
  - local-llm
  - byok
ManifestType: defaultLocale
ManifestVersion: 1.9.0
`,
    },
    {
      relpath: `${base}/${packageId}.installer.yaml`,
      content: `# GENERATED by scripts/channel-manifest.ts — do not edit by hand.
PackageIdentifier: ${packageId}
PackageVersion: ${version}
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
Installers:
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: xr.exe
        PortableCommandAlias: xr
    InstallerUrl: ${zipUrl}
    InstallerSha256: ${sha}
ManifestType: installer
ManifestVersion: 1.9.0
`,
    },
  ];
}

// ── Scoop manifest ─────────────────────────────────────────────────────────

export function renderScoop(manifest: ReleaseManifest, sums?: Map<string, string>): string {
  const id = manifest.identity;
  const sha = sums ? requireSha(sums.get("xr-windows-x64.zip"), "xr-windows-x64.zip") : "SHA256_XR_WINDOWS_X64_ZIP";
  return (
    JSON.stringify(
      {
        "#": "GENERATED by scripts/channel-manifest.ts — do not edit by hand.",
        version: id.version,
        description: id.description,
        homepage: id.repo,
        license: id.license,
        architecture: {
          "64bit": {
            url: downloadUrl(manifest, "xr-windows-x64.zip"),
            hash: sha,
          },
        },
        bin: "xr.exe",
        checkver: {
          github: id.repo,
        },
        autoupdate: {
          architecture: {
            "64bit": {
              url: `https://github.com/${id.repo.split("/").slice(-2).join("/")}/releases/download/v$version/xr-windows-x64.zip`,
            },
          },
        },
      },
      null,
      2,
    ) + "\n"
  );
}

// ── Channel file inventory (committed templates) ───────────────────────────

export function renderedTemplates(manifest: ReleaseManifest): RenderedChannelFile[] {
  return [
    { relpath: "homebrew/xr.rb", content: renderHomebrewFormula(manifest) },
    ...renderWinget(manifest),
    { relpath: "scoop/xr.json", content: renderScoop(manifest) },
  ];
}

export function renderedStamped(manifest: ReleaseManifest, sums: Map<string, string>): RenderedChannelFile[] {
  return [
    { relpath: "homebrew/xr.rb", content: guard(renderHomebrewFormula(manifest, sums)) },
    ...renderWinget(manifest, sums).map((f) => ({ ...f, content: guard(f.content) })),
    { relpath: "scoop/xr.json", content: guard(renderScoop(manifest, sums)) },
  ];
}

function requireSha(sha: string | undefined, key: string): string {
  if (!sha || !/^[0-9a-f]{64}$/.test(sha)) {
    throw new Error(`channel stamping failed closed: no sha256 for ${key} in SHA256SUMS (one canonical build — Art. XXII)`);
  }
  return sha;
}

function guard(content: string): string {
  if (/SHA256_[A-Z0-9_]+/.test(content)) {
    throw new Error("channel stamping failed closed: unstamped placeholder survived — every channel must carry signed checksums");
  }
  return `# ${STAMP_GUARD}\n${content}`;
}

// ── CLI ────────────────────────────────────────────────────────────────────

function arg(flag: string): string | undefined {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

async function main(): Promise<void> {
  const manifest = loadManifest();

  if (process.argv.includes("--check")) {
    const expected = renderedTemplates(manifest);
    const problems: string[] = [];
    for (const f of expected) {
      const path = join(PACKAGING_DIR, f.relpath);
      if (!existsSync(path)) {
        problems.push(`${f.relpath}: missing — every channel config must be generated (run \`bun run channel:sync\`)`);
        continue;
      }
      const actual = readFileSync(path, "utf8");
      if (actual !== f.content) {
        problems.push(`${f.relpath}: drifted from the release manifest (run \`bun run channel:sync\`) — Art. XXII forbids channel drift`);
      }
    }
    if (problems.length > 0) {
      for (const p of problems) console.error(`[channel:check] FAIL — ${p}`);
      process.exit(1);
    }
    console.log(
      `[channel:check] ok — ${expected.length} channel configs in sync with release v${manifest.identity.version} (one canonical build, many channels)`,
    );
    return;
  }

  if (process.argv.includes("--write")) {
    for (const f of renderedTemplates(manifest)) {
      const path = join(PACKAGING_DIR, f.relpath);
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, f.content);
      console.log(`[channel:sync] wrote ${f.relpath}`);
    }
    return;
  }

  if (process.argv.includes("--stamp")) {
    const sumsPath = arg("--sums") ?? join(ROOT, "dist", "SHA256SUMS");
    const outDir = arg("--out") ?? join(ROOT, "dist", "channels");
    if (!existsSync(sumsPath)) {
      console.error(`[channel:stamp] FAIL — SHA256SUMS not found at ${sumsPath}`);
      process.exit(1);
    }
    const sums = parse(readFileSync(sumsPath, "utf8"));
    const files = renderedStamped(manifest, sums);
    for (const f of files) {
      const path = join(outDir, f.relpath);
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, f.content);
      console.log(`[channel:stamp] stamped ${f.relpath}`);
    }
    console.log(`[channel:stamp] ok — ${files.length} channel configs bound to the signed canonical build`);
    return;
  }

  console.error("usage: bun run scripts/channel-manifest.ts [--write|--check|--stamp --sums SHA256SUMS --out DIR]");
  process.exit(2);
}

if (import.meta.main) {
  await main();
}
