/**
 * XR 5.3 — Outcome-Oriented Journeys — Canonical definitions for
 * personal, developer, research, customer/business, sales, projects/meetings/docs,
 * scheduling/communication, finance/operations.
 *
 * Each journey defines trigger/intent, context package, workflow version,
 * agent/deterministic/human nodes, capabilities, authority/approvals,
 * artifacts/records, verified outcome, cost/time, audit/provenance, failure/recovery.
 */

import type { JourneyDefinition } from './operating-types.ts';

export const JOURNEY_DEFINITIONS: JourneyDefinition[] = [
  {
    id: 'personal-knowledge-capture',
    name: 'Personal Knowledge & Task Capture',
    category: 'personal_knowledge',
    description: 'Capture meeting notes, extract tasks, summarize, create document artifact and tasks with provenance.',
    trigger: { kind: 'intent', intentPattern: 'capture notes|create tasks|meeting notes' },
    context: { tiers: ['instructions', 'data'], includeUserMemory: true, maxItems: 15, locality: 'private', sensitivityMax: 'confidential' },
    workflow: { definitionId: 'personal-knowledge-v1', version: 1, nodes: [
      { id: 'trigger', kind: 'trigger', name: 'Intent trigger' },
      { id: 'parse_notes', kind: 'deterministic', name: 'Parse notes and extract tasks' },
      { id: 'summarize', kind: 'agentic', name: 'Summarize and suggest tags' },
      { id: 'review_tasks', kind: 'human_review', name: 'Review extracted tasks' },
      { id: 'create_tasks', kind: 'business_record', name: 'Create tasks' },
      { id: 'create_doc', kind: 'artifact_output', name: 'Create document artifact' },
      { id: 'complete', kind: 'completion', name: 'Complete' },
    ], capabilities: ['business:tasks.create', 'business:documents.create', 'context:package.build'], authority: { requiredRole: 'member', requiresApproval: false } },
    outcomes: { metrics: ['tasks_created', 'document_created', 'duration_ms'], verifiedOutcomeType: 'personal_knowledge_captured', costBudget: { maxUsd: 0.10, maxTokens: 8000, maxDurationMs: 30000 }, successCriteria: ['document artifact exists', 'tasks linked to project if detected', 'provenance intact'] },
    artifacts: ['document', 'record_snapshot'],
    privacy: 'private',
    version: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'developer-project-delivery',
    name: 'Developer Project Delivery',
    category: 'developer_project',
    description: 'Create project, validate, create milestones, generate plan doc, approval, activate.',
    trigger: { kind: 'event', eventType: 'project.created' },
    context: { tiers: ['instructions', 'data'], includeUserMemory: false, maxItems: 20, locality: 'local', sensitivityMax: 'internal' },
    workflow: { definitionId: 'developer-project-v1', version: 1, nodes: [
      { id: 'trigger', kind: 'trigger', name: 'Project created' },
      { id: 'validate', kind: 'deterministic', name: 'Validate project' },
      { id: 'create_milestones', kind: 'deterministic', name: 'Create milestones' },
      { id: 'generate_plan', kind: 'agentic', name: 'Generate project plan doc' },
      { id: 'approve_plan', kind: 'human_approval', name: 'Owner approves plan' },
      { id: 'activate_project', kind: 'business_record', name: 'Activate project' },
      { id: 'create_docs_folder', kind: 'tool_action', name: 'Create docs folder' },
      { id: 'complete', kind: 'completion', name: 'Complete' },
    ], capabilities: ['business:projects.create', 'business:tasks.create', 'business:documents.create'], authority: { requiredRole: 'manager', requiresApproval: true } },
    outcomes: { metrics: ['project_active', 'milestones_created', 'plan_doc_created'], verifiedOutcomeType: 'project_delivered', costBudget: { maxUsd: 0.20, maxTokens: 10000, maxDurationMs: 60000 }, successCriteria: ['project status active', 'milestones exist', 'plan doc artifact'] },
    artifacts: ['document', 'record_snapshot'],
    privacy: 'local',
    version: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'research-evidence-report',
    name: 'Research Evidence Report',
    category: 'research_evidence',
    description: 'Research topic, evidence ledger, synthesis, report artifact, review, publish to knowledge base with provenance.',
    trigger: { kind: 'intent', intentPattern: 'research|evidence|report' },
    context: { tiers: ['instructions', 'data', 'quarantine'], includeUserMemory: true, maxItems: 30, locality: 'hybrid', sensitivityMax: 'internal' },
    workflow: { definitionId: 'research-evidence-v1', version: 1, nodes: [
      { id: 'trigger', kind: 'trigger', name: 'Research intent' },
      { id: 'plan_queries', kind: 'deterministic', name: 'Plan queries' },
      { id: 'search_rank', kind: 'agentic', name: 'Search and rank sources' },
      { id: 'extract_synthesize', kind: 'agentic', name: 'Extract and synthesize' },
      { id: 'report_artifact', kind: 'artifact_output', name: 'Generate report artifact' },
      { id: 'review_report', kind: 'human_review', name: 'Review report' },
      { id: 'publish_kb', kind: 'business_record', name: 'Publish KB article' },
      { id: 'complete', kind: 'completion', name: 'Complete' },
    ], capabilities: ['research:search', 'research:synthesize', 'business:knowledge.create', 'context:provenance'], authority: { requiredRole: 'member', requiresApproval: false } },
    outcomes: { metrics: ['sources_count', 'evidence_blocks', 'report_citations', 'kb_published'], verifiedOutcomeType: 'research_report_verified', costBudget: { maxUsd: 0.50, maxTokens: 15000, maxDurationMs: 120000 }, successCriteria: ['report artifact with citations', 'KB article draft', 'trust score > threshold'] },
    artifacts: ['research_report', 'document'],
    privacy: 'hybrid',
    version: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'customer-support-triage',
    name: 'Customer Support Triage',
    category: 'customer_crm',
    description: 'Ticket inbound, classify priority, check SLA, lookup contact, escalate if urgent, suggest KB, assign, notify.',
    trigger: { kind: 'event', eventType: 'ticket.created' },
    context: { tiers: ['instructions', 'data'], includeUserMemory: false, maxItems: 15, locality: 'private', sensitivityMax: 'confidential' },
    workflow: { definitionId: 'customer-support-v1', version: 1, nodes: [
      { id: 'trigger', kind: 'trigger', name: 'Ticket created' },
      { id: 'classify', kind: 'deterministic', name: 'Classify priority and SLA' },
      { id: 'lookup_contact', kind: 'tool_action', name: 'Lookup contact' },
      { id: 'check_urgent', kind: 'branch', name: 'Is urgent?' },
      { id: 'escalate', kind: 'notification', name: 'Escalate to support role' },
      { id: 'suggest_kb', kind: 'agentic', name: 'Suggest KB articles' },
      { id: 'review_suggestion', kind: 'human_review', name: 'Review suggestion' },
      { id: 'assign_ticket', kind: 'business_record', name: 'Assign ticket' },
      { id: 'notify_contact', kind: 'notification', name: 'Notify contact' },
      { id: 'complete', kind: 'completion', name: 'Complete' },
    ], capabilities: ['business:support.triage', 'business:contacts.read', 'context:retrieval'], authority: { requiredRole: 'member', requiresApproval: false } },
    outcomes: { metrics: ['ticket_assigned', 'sla_tracked', 'kb_suggested', 'first_response_ms'], verifiedOutcomeType: 'support_triaged', costBudget: { maxUsd: 0.10, maxTokens: 5000, maxDurationMs: 30000 }, successCriteria: ['ticket assigned', 'SLA timer set', 'KB suggestions attached'] },
    artifacts: ['communication', 'record_snapshot'],
    privacy: 'private',
    version: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sales-deal-progression',
    name: 'Sales Deal Progression',
    category: 'sales_followup',
    description: 'Deal created/moved, validate transition, check required fields, branch high-value approval, move deal, forecast, follow-up task, invoice proposal.',
    trigger: { kind: 'event', eventType: 'deal.created' },
    context: { tiers: ['instructions', 'data'], includeUserMemory: false, maxItems: 20, locality: 'private', sensitivityMax: 'confidential' },
    workflow: { definitionId: 'sales-deal-v1', version: 1, nodes: [
      { id: 'trigger', kind: 'trigger', name: 'Deal event' },
      { id: 'validate_transition', kind: 'deterministic', name: 'Validate stage transition' },
      { id: 'check_fields', kind: 'deterministic', name: 'Check required fields' },
      { id: 'check_value', kind: 'branch', name: 'Value > threshold?' },
      { id: 'approve_high_value', kind: 'human_approval', name: 'Manager approves high-value' },
      { id: 'move_deal', kind: 'business_record', name: 'Move deal' },
      { id: 'calc_forecast', kind: 'deterministic', name: 'Calculate forecast' },
      { id: 'notify_owner', kind: 'notification', name: 'Notify owner' },
      { id: 'followup', kind: 'tool_action', name: 'Create follow-up task or invoice' },
      { id: 'complete', kind: 'completion', name: 'Complete' },
    ], capabilities: ['business:deals.move', 'business:finance.create_invoice'], authority: { requiredRole: 'member', requiresApproval: true } },
    outcomes: { metrics: ['deal_stage_moved', 'forecast_updated', 'followup_created', 'invoice_proposed'], verifiedOutcomeType: 'deal_progressed', costBudget: { maxUsd: 0.05, maxTokens: 3000, maxDurationMs: 20000 }, successCriteria: ['deal stage moved', 'forecast updated', 'follow-up task created'] },
    artifacts: ['record_snapshot', 'document'],
    privacy: 'private',
    version: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'project-meeting-to-doc',
    name: 'Project Meeting to Documentation',
    category: 'projects_meetings_docs',
    description: 'Meeting ended, parse transcript, extract action items, summarize, create notes doc artifact, review, create tasks, update meeting.',
    trigger: { kind: 'event', eventType: 'meeting.ended' },
    context: { tiers: ['instructions', 'data'], includeUserMemory: false, maxItems: 25, locality: 'private', sensitivityMax: 'restricted' },
    workflow: { definitionId: 'meeting-doc-v1', version: 1, nodes: [
      { id: 'trigger', kind: 'trigger', name: 'Meeting ended' },
      { id: 'parse_transcript', kind: 'deterministic', name: 'Parse transcript' },
      { id: 'summarize', kind: 'agentic', name: 'Generate summary' },
      { id: 'notes_artifact', kind: 'artifact_output', name: 'Create notes doc artifact' },
      { id: 'review_notes', kind: 'human_review', name: 'Organizer reviews notes' },
      { id: 'create_tasks', kind: 'business_record', name: 'Create tasks for action items' },
      { id: 'update_meeting', kind: 'business_record', name: 'Update meeting notes' },
      { id: 'complete', kind: 'completion', name: 'Complete' },
    ], capabilities: ['business:meetings.read', 'business:documents.create', 'business:tasks.create'], authority: { requiredRole: 'member', requiresApproval: false } },
    outcomes: { metrics: ['notes_doc_created', 'tasks_created_from_transcript', 'meeting_updated'], verifiedOutcomeType: 'meeting_documented', costBudget: { maxUsd: 0.20, maxTokens: 10000, maxDurationMs: 45000 }, successCriteria: ['notes doc artifact exists', 'tasks linked to meeting', 'transcript provenance preserved'] },
    artifacts: ['meeting_notes', 'document', 'record_snapshot'],
    privacy: 'private',
    version: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'scheduling-meeting-coordination',
    name: 'Scheduling & Meeting Coordination',
    category: 'scheduling_communication',
    description: 'Schedule meeting intent, check availability, propose times, approval, create meeting, notify attendees, agenda doc optional.',
    trigger: { kind: 'intent', intentPattern: 'schedule meeting|create meeting|book meeting' },
    context: { tiers: ['instructions', 'data'], includeUserMemory: true, maxItems: 20, locality: 'private', sensitivityMax: 'internal' },
    workflow: { definitionId: 'scheduling-v1', version: 1, nodes: [
      { id: 'trigger', kind: 'trigger', name: 'Schedule intent' },
      { id: 'check_availability', kind: 'deterministic', name: 'Check availability' },
      { id: 'conflict_check', kind: 'branch', name: 'Conflict?' },
      { id: 'propose_times', kind: 'notification', name: 'Propose times' },
      { id: 'confirm', kind: 'human_approval', name: 'Organizer confirms' },
      { id: 'create_meeting', kind: 'business_record', name: 'Create meeting' },
      { id: 'invite_attendees', kind: 'notification', name: 'Invite attendees' },
      { id: 'agenda_doc', kind: 'artifact_output', name: 'Create agenda doc' },
      { id: 'complete', kind: 'completion', name: 'Complete' },
    ], capabilities: ['business:calendar.check', 'business:meetings.create', 'control:notification'], authority: { requiredRole: 'member', requiresApproval: true } },
    outcomes: { metrics: ['meeting_scheduled', 'calendar_events_created', 'invites_sent', 'scheduling_duration_ms'], verifiedOutcomeType: 'meeting_scheduled', costBudget: { maxUsd: 0.05, maxTokens: 2000, maxDurationMs: 20000 }, successCriteria: ['meeting record created', 'calendar events', 'invites notified'] },
    artifacts: ['document', 'record_snapshot'],
    privacy: 'private',
    version: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'finance-invoice-from-deal',
    name: 'Finance Invoice from Deal',
    category: 'finance_operations',
    description: 'Deal won event, validate, create invoice draft, finance manager approval if high-value, create invoice, send (elevated approval external write).',
    trigger: { kind: 'event', eventType: 'deal.won' },
    context: { tiers: ['instructions', 'data'], includeUserMemory: false, maxItems: 15, locality: 'private', sensitivityMax: 'confidential' },
    workflow: { definitionId: 'finance-invoice-v1', version: 1, nodes: [
      { id: 'trigger', kind: 'trigger', name: 'Deal won' },
      { id: 'validate', kind: 'deterministic', name: 'Validate deal and contact' },
      { id: 'draft_invoice', kind: 'deterministic', name: 'Create invoice draft' },
      { id: 'approve_invoice', kind: 'human_approval', name: 'Finance manager approves' },
      { id: 'create_invoice', kind: 'business_record', name: 'Create invoice' },
      { id: 'send_invoice', kind: 'tool_action', name: 'Send invoice (external write)' },
      { id: 'complete', kind: 'completion', name: 'Complete' },
    ], capabilities: ['business:finance.create_invoice', 'business:finance.send_invoice'], authority: { requiredRole: 'manager', requiresApproval: true } },
    outcomes: { metrics: ['invoice_created', 'invoice_sent', 'total_value', 'linked_to_deal'], verifiedOutcomeType: 'invoice_issued', costBudget: { maxUsd: 0.10, maxTokens: 3000, maxDurationMs: 30000 }, successCriteria: ['invoice created', 'linked to deal', 'sent if approved', 'reversible via cancel'] },
    artifacts: ['document', 'record_snapshot'],
    privacy: 'private',
    version: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
];

export function getJourneyById(id: string): JourneyDefinition | undefined {
  return JOURNEY_DEFINITIONS.find(j => j.id === id);
}

export function listJourneysByCategory(category: string): JourneyDefinition[] {
  return JOURNEY_DEFINITIONS.filter(j => j.category === category);
}

export function listAllJourneys(): JourneyDefinition[] {
  return JOURNEY_DEFINITIONS.filter(j => j.active);
}
